### ISSUE TITLE
K8s namespace deletion hangs with VaultAuth and VaultConnection resources

### ISSUE THREAD

**Issue by dnlopes** [hashicorp/vault-secrets-operator#100]
**Describe the bug**
After playing around with VSO with Minikube, deleting a namespace containing VSO custom resources hangs indefinitely.

**To Reproduce**

1. minikube start --kubernetes-version=v1.23.17
2. kubectl create namespace sample
3. kubectl config set-context --current --namespace=sample
4. helm repo add hashicorp https://helm.releases.hashicorp.com && helm repo update
5. helm upgrade --namespace sample --install vault-secrets-operator hashicorp/vault-secrets-operator --version 0.1.0-beta
6. deploy K8s resources below
7. wait 30 seconds
8. kubectl delete namespace sample

The delete will hang. The namespace will appear as `Terminating`. Now run:
```
kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n sample
```

and check that the last two resources in the namespace are of type `VaultAuth` and `VaultConnection`.

```yaml
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuth
metadata:
  name: vault-auth-sample
  namespace: sample
spec:
  vaultConnectionRef: vault-connection-sample
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: sample
    serviceAccount: sample
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultConnection
metadata:
  name: vault-connection-sample
  namespace: sample
spec:
  address: http://host.docker.internal:8200
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-1
  namespace: sample
type: Opaque
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  namespace: sample
  name: vault-secret-1
spec:
  vaultAuthRef: vault-auth-sample
  mount: secret
  type: kv-v2
  hmacSecretData: true
  name: sample/aws
  refreshAfter: 5s
  destination:
    name: sample-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample
```

**Expected behavior**
K8s namespace should be deleted as expected.

**Environment**
* Kubernetes version: 1.23.17
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): Minikube
  * Other configuration options or runtime services (istio, etc.):
* vault-secrets-operator version: 0.1.0-beta
