### ISSUE TITLE
VaultPKISecret AltNames not of type string with Helm templating

### ISSUE THREAD

**Issue by nrogerarkhn** [hashicorp/vault-secrets-operator#115]
**Describe the bug**
`2023-04-06T09:34:29Z	ERROR	Reconciler error	{"controller": "vaultpkisecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultPKISecret", "VaultPKISecret": {"name":"front-certificate","namespace":"ns"}, "namespace": "ns", "name": "front-certificate", "reconcileID": "c64d90ee-c03e-4cc9-a275-f4a9a08c0c3e", "error": "Error making API request.\n\nURL: PUT http://platform-vault.ns.svc.cluster.local:8200/v1/pki/issue/redacted\nCode: 400. Errors:\n\n* Field validation failed: error converting input [redacted.fqdn] for field \"alt_names\": '' expected type 'string', got unconvertible type '[]interface {}', value: '[redacted.fqdn]'"}`

**To Reproduce**
1. Deploy application with the following yaml file with the following VSO custom resources as a template in a Helm dependency.
```yaml
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultConnection
metadata:
  namespace: ns
  name: vso-connection
spec:
  address: http://platform-vault.ns.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuth
metadata:
  namespace: ns
  name: vso-auth
spec:
  vaultConnectionRef: vso-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: default
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultPKISecret
metadata:
  namespace: ns
  name: front-certificate
spec:
  vaultAuthRef: vso-auth
  mount: pki
  name: redacted
  commonName: {{ (.Values.global).fqdn | quote }}
  altNames:
    - {{ (.Values.global).fqdn | quote }}
  format: pem
  privateKeyFormat: pem
  expiryOffset: 1s
  ttl: 60s
  namespace: ns
  revoke: true
  clear: true
  destination:
    create: true
    name: front-cert
    type: kubernetes.io/tls
```
2. Look into operator logs to find above error.

**Expected behavior**
The file is ok and the secret is created.

**Environment**
* Kubernetes version: 
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): k3s
  * Other configuration options or runtime services (istio, etc.): Helm dependency, deployed by ArgoCD
* vault-secrets-operator version: 0.1.0-beta

Don't hesitate if anything is unclear!
Thanks in advance and have a great day :)
