### ISSUE TITLE
K8S secret is not re-created if deleted for some bad reason

### ISSUE THREAD

**Issue by sebglon** [hashicorp/vault-secrets-operator#124]
**Describe the bug**
The K8S is not re-created during the sync phase of the vaultstaticsecret.

**To Reproduce**
1. create a vaultstatic secret
2. wait the K8S secret creation
3. drop the K8S secret generated
5. on the operator log we can see the sync log:
```
 DEBUG    events    Secret sync not required    {"type": "Normal", "object": {"kind":"VaultS │
│ taticSecret","namespace":"minio","name":"minio-encrypted-aws-root-key","uid":"98bb47f6-7aa5-41f3-b04c-45c1ae2d5ebe","apiVer ││ sion":"secrets.hashicorp.com/v1alpha1","resourceVersion":"196528971"}, "reason": "SecretSync"}
```

But the K8S secret is not more existing

**Expected behavior**
the K8S secret is re-created

**Environment**
* Kubernetes version:  1.22.2
* vault-secrets-operator version: 0.11.0

**Comment by sebglon** [comment]
hi,
an example of the `VaultStaticSecret`:
```
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  namespace: monitoring
  name: ec2-keys
spec:
  vaultAuthRef: check-backups
  mount: secret
  type: kv-v2
  name: consul-backup/aws
  refreshAfter: 5m
  destination:
    name: ec2-keys
    create: true
```
