### ISSUE TITLE
Support secret templating

### ISSUE THREAD

**Issue by nimjor** [hashicorp/vault-secrets-operator#135]
**Is your feature request related to a problem? Please describe.**
To really be practical and cover most potential use cases, the VaultStaticSecret and VaultDynamicSecret types should allow templating based on the values retrieved from Vault.

**Describe the solution you'd like**
We should be able to use Go templating or Consul Template, similar to what can be done using the Vault agent annotations.  For example, I want to be able to use the Artifactory Vault dynamic secrets plugin/engine to generate temporary Artifactory credentials that can be injected into a `kubernetes.io/dockerconfigjson` secret to use for container image pull secrets.

**Describe alternatives you've considered**
I can already do as described above using `external-secrets.io`

**Additional context**
How this is done with external-secrets:
```yaml
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-dynamic
  namespace: demo
spec:
  path: "/artifactory/token/demo"
  method: "GET"
  provider:
    server: "https://vault-dev.tools.demo.com"
    auth:
      kubernetes:
        mountPath: "k8s-platform"
        role: "demo-tools-access-read"
        serviceAccountRef:
          name: "demo"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: image-pull-dynamic
  namespace: demo
spec:
  refreshInterval: "3600s"
  target:
    name: image-pull-dynamic
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "containers.artifactory-dev.tools.demo.com": {
                "auth": "{{ list .username ":" .access_token | join "" | b64enc }}",
                "email": "demo@example.com",
                "password": "{{ .access_token }}",
                "username": "{{ .username }}"
              }
            }
          }
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: vault-dynamic
```

**Comment by benashz** [comment]
Thanks for your valuable feedback @nimjor! Adding template support is definitely a feature we are considering in the near future.

**Comment by TheLonelyGhost** [comment]
Whoa! I didn't realize ExternalSecret resources could do that! That's awesome! Seems to add support to the proposal from #120

**Comment by linuxbsdfreak** [comment]
This feature is already present under https://github.com/ricoberger/vault-secrets-operator#using-templated-secrets 

I have been using the above operator and it works really well. Would be nice to have this feature.

**Comment by kennedn** [comment]
Seconding this. Until this operator has templating, it's use cases are going to be severely narrowed.

**Comment by kschoche** [comment]
Hi @BOsterbuhr - adding templating support is on our upcoming roadmap, we will have more updates on that coming soon. Right now we support the built-in types that Kubernetes [automatically templates](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types).

As far as supporting `.dockerconfigjson`, I believe this should already work by setting the `spec.destination.type` field to `kubernetes.io/dockerconfigjson`?

Here is an example which uses a KV secret to do the same, I've been meaning to put this into a public document.. if it doesnt work feel free to open a separate issue because it *should*:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: awesomeapps
  name: foo
spec:
  type: kv-v2
  mount: kvv2
  path: docker/config
  # dest k8s secret
  destination:
    name: myregistryKey  # <-- this is your imagePullSecret name
    create: true
    type: "kubernetes.io/dockerconfigjson"
---
apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: awesomeapps
spec:
  containers:
    - name: foo
      image: janedoe/awesomeapp:v1
  imagePullSecrets:
   - name: myregistrykey
```

```shell
# Example vault command to load the dockerconfig into a kv:
 vault kv put kvv2/docker/config .dockerconfigjson=`cat ~/.docker/config.json`
```
