### ISSUE TITLE
Static Secret always returns Vault secret was empty from HCP Vault

### ISSUE THREAD

**Issue by CraightonH** [hashicorp/vault-secrets-operator#162]
**Describe the bug**
The operator seems to be incompatible with HCP Vault, the hashicorp managed vault service. I have successfully authenticated the operator with vault, however I cannot get a `VaultStaticSecret`. 

**To Reproduce**
After setting up the operator, apply the following file with `kubectl`
```
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  namespace: hashicorp
  name: test
spec:
  type: kv-v2
  namespace: admin
  mount: kubernetes
  name: test
  refreshAfter: 60s
  destination:
    create: true
    name: test
    type: Opaque
```
I tested changing `namespace`, `mount`, and `name` to invalid values with the same result: `Vault secret was empty`

**Expected behavior**
I expect the secret located at the path `admin/kubernetes/test` to be deployed into the cluster as a `Secret`

**Environment**
* vault-secrets-operator version: `0.1.0-beta`

**Additional context**
I have found the biggest difference between HCP Vault and local vault is that HCP's `root` is instead named `admin`. To get most vault services to work I have to specify the namespace `admin`. For example, to retrieve the same secret from the vault API, I can run:
```
curl https://[vault address]/v1/kubernetes/data/test \
-H "X-Vault-Namespace: admin"
-H "X-Vault-Token: [token]"
```
or embed the namespace in the URL like so
```
curl https://[vault address]/v1/admin/kubernetes/data/test \
-H "X-Vault-Token: [token]"
```
Either I've overlooked some config, or it seems to me that the operator assumes the default namespace is `root` and appends the `VaultStaticSecret`'s `namespace` instead of replaces the namespace.
