### ISSUE TITLE
 Add auth-path in VaultAuth 

### ISSUE THREAD

**Issue by jtaguinod** [hashicorp/vault-secrets-operator#177]
**Is your feature request related to a problem? Please describe.**

I have multiple kubernetes cluster that wants to use only one Vault, so I had to add multiple Authentication method using the name of the cluster but the type is kubernetes. In the previous vault secrets injector setup, I was able to use the auth-path as annotation, however using the vault-secrets-operator I am not able to modify the path of the method other than kubernetes nor add an auth-path. Hence the logs is showing me Code 403. Errors: Permission denied because the URL  is all pointing to https://x.x.x:8200/v1/auth/kubernetes/login

In the authentication method I use the name of the cluster and the type as Kubernetes.

**Describe the solution you'd like**
Add auth-path in the  VaultAuth

**Describe alternatives you've considered**

**Additional context**

**Comment by benashz** [comment]
Hi @jtaguinod, would you mind providing us with an example of your `VaultAuth` and `VaultConnection` Custom resource(s), please feel to redact where necessary. That will help us to better understand the issue that you are facing.

Thanks,

Ben

**Comment by togrulazizli** [comment]
@jtaguinod In case if you haven't solved the problem:
The way to specify auth-path is to define it to "mount" under VaultAuth object

```
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuth
metadata:
  namespace: vault-secrets-operator-system
  name: devops-auth
spec:
  vaultConnectionRef: devops-conn
  # Method to use when authenticating to Vault.
  method: kubernetes --------> Type of authentication which is defined in specific Authentication Method in Vault server
  # Mount to use when authenticating to auth method.
  mount: dev-cluster ---------> Name of the Authentication Method from Vault
  kubernetes:
    role: example
    serviceAccount: default
```

@benashz 
Moreover,  by default the Helm Chart and documentation use /auth/kubernetes/login path and there becomes confusion between "type" "kubernetes" and "vault authentication method" "kubernetes" (both in Vault terminology). 
The main issue is even-though the Vault server has no authentication method named "kubernetes" it still returns 
```
URL: PUT https://x.x.x.x/v1/auth/kubernetes/login
Code: 403. Errors:

* permission denied
```
 error instead of "there is no such auth method or smt like that" which is confusing and misleading for troubleshooting.
Request:
1. It would be better if documentation updated to use "kubernetes-cluster-auth" or smt like that instead of just "kubernetes" for "mount" in VaultAuth CRD to avoid confusion.
2. Improve error handling in Vault so it won't return permission denied error when request was made to auth method which does not exist in Vault server
