### ISSUE TITLE
[VaultPKISecret] Populate ca.crt from the vault issuing_ca

### ISSUE THREAD

**Issue by djds** [hashicorp/vault-secrets-operator#178]
Populate `ca.crt` from the vault `issuing_ca` field the Kubernetes secret created by `VaultPKISecret` if the target secret is of type `kuberntes.io/tls`. Many Kubernetes applications expect a CA to be located at that key and this would obviate the need for separate CA `ConfigMaps` or `Secrets` in many cases. This is especially useful because Vault works great as a cluster CA, but would also simplify the rollout of new trust anchors when the CA is updated or rotated.

**Comment by nia-potato** [comment]
I also have this requirement, and is blocking deployment, we cannot expect to not auto populate `caCertSecret` when rolling out vso to clusters.

**Comment by tvoran** [comment]
BTW, this can now be done using a template:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: example
spec:
  ...
  destination:
    name: pki1
    transformation:
      templates:
          ca.crt:
            text: |
              {{- printf "%s" (get .Secrets "issuing_ca") -}}
```
