### ISSUE TITLE
Vault CA required for VaultPKISecret in different namespace than default VaultConnection

### ISSUE THREAD

**Issue by andrejvanderzee** [hashicorp/vault-secrets-operator#192]
**Describe the bug**

When I run the vault-secrets-operator in namespace `kube-system` with a default VaultConnection, and define a VaultPKISecret in namespace `tenant`, then I must copy the Vault CA secret to the `tenant`namespace.

**To Reproduce**

Deploy vault-secrets-operator in `kube-system`with a default VaultConnection. Then in namespace `tenant`deploy:

```
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultPKISecret
metadata:
  name: testing
  namespace: tenant
spec:
  mount: eks/pki
  name: server
  destination:
    create: true
    name: vault-secrets-operator-test
    type: kubernetes.io/tls
  commonName: test.example.com
  format: pem
  revoke: true
  clear: true
  ttl: "5m"
  ```

It results in the following error:

```
2023-05-19T16:30:35Z	ERROR	Reconciler error	{"controller": "vaultpkisecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultPKISecret", "VaultPKISecret": {"name":"testing","namespace":"tenant"}, "namespace": "tenant", "name": "testing", "reconcileID": "23d80658-96f3-48f2-be0b-58b6c504d893", "error": "Secret \"vault-ca\" not found"}
```

Note When I deploy the VaultPKISecret in `kube-system`, it works as expected.

**Expected behavior**

Use the `vault-ca` in namespace `kube-system` where the default VaultConnection is defined.

**Environment**

kubernetes: EKS v1.25.6
vault-secrets-operator: latest master (commit 07cc2e0d004e8a07c1ff19c080f96815a8190d0f)
