### ISSUE TITLE
Vault secret empty but appears some hours later with VaultStaticSecret

### ISSUE THREAD

**Issue by nrogerarkhn** [hashicorp/vault-secrets-operator#206]
**Describe the bug**
My Vault Static Secret throws a Vault secret empty error. When I get into the Vault container and kv get it manually, it does appear. I stop getting the error a few hours later. It has happened twice over the last week, when I initially created the Vault and when I recreated it with new values.
**EDIT:** I don't seem to have the problem on a fresh installation, might be something else on our stack, but nothing should interact with Vault...

**To Reproduce**
1. Deploy Vault and VSO via Helm charts on ArgoCD (didn't try without it)
2. Populate Vault with values in the KV store
3. Create VSO Connection, Auth and Static Secrets getting those values in the KV store
4. The Static Secrets throw the Vault secret empty error
5. Wait a few hours (in my case, go to sleep and come back the next day)
6. The secret is synchronized and the Static Secret says Secret sync not required

Application deployment:

```yaml
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultConnection
metadata:
  name: vso-connection
spec:
  address: http://{{ .Release.Name }}-vault.ns.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuth
metadata:
  name: vso-auth
spec:
  vaultConnectionRef: vso-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: default
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  name: vss-postgres-root-password
spec:
  vaultAuthRef: vso-auth
  mount: secrets
  type: kv-v2
  name: postgres-root
  refreshAfter: 60s
  destination:
    create: true
    name: postgres-root-password
```
I have like a dozen other passwords but their manifest look exactly the same.

`kubectl describe` output:
```
Name:         vss-postgres-root-password
Labels:       argocd.argoproj.io/instance=platform
Annotations:  <none>
API Version:  secrets.hashicorp.com/v1alpha1
Kind:         VaultStaticSecret
Metadata:
  Creation Timestamp:  2023-05-16T12:30:23Z
  Generation:          5
  Managed Fields:
    API Version:  secrets.hashicorp.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:argocd.argoproj.io/instance:
      f:spec:
        .:
        f:destination:
          .:
          f:create:
          f:name:
        f:hmacSecretData:
        f:mount:
        f:name:
        f:refreshAfter:
        f:type:
        f:vaultAuthRef:
    Manager:      argocd-controller
    Operation:    Update
    Time:         2023-05-23T08:58:56Z
    API Version:  secrets.hashicorp.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:secretMAC:
    Manager:         vault-secrets-operator
    Operation:       Update
    Subresource:     status
    Time:            2023-05-23T23:13:42Z
  Resource Version:  9328423
  UID:               8d4db896-ddb0-4259-acea-7da403ca167f
Spec:
  Destination:
    Create:          true
    Name:            postgres-root-password
  Hmac Secret Data:  true
  Mount:             secrets
  Name:              postgres-root
  Refresh After:     60s
  Type:              kv-v2
  Vault Auth Ref:    vso-auth
Status:
  Secret MAC:  *don't know if it's a sensitive value but there's one*
Events:
  Type    Reason      Age                       From               Message
  ----    ------      ----                      ----               -------
  Normal  SecretSync  3m55s (x11021 over 7d2h)  VaultStaticSecret  Secret sync not required
```

**Expected behavior**
The Vault Static Secret is synchronized few moments after its creation, not hours.

**Environment**
* Kubernetes version: 1.26.3
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): k3s
  * Other configuration options or runtime services (istio, etc.): deployed by ArgoCD
* vault-secrets-operator version: 0.1.0-beta

**Additional context**
The first time, I created the VSS in the afternoon and it was synchronized at 6:14AM, and this time I created them yesterday afternoon as well but it was synchronized at 1:14AM, so there doesn't seem to be a fixed duration to wait before the secret is "found".

Thank you very much in advance!
