### ISSUE TITLE
CRD version upgrades create incompatibility with previously installed versions

### ISSUE THREAD

**Issue by maj** [hashicorp/vault-secrets-operator#283]
I installed the initial release of the Vault Secrets Operator via Helm. This created a "default" VaultConnection in the "vault-secrets-operator-system" namespace.

When I later upgraded to the 0.1.0 version I got errors like:
```
E0711 02:25:56.448952       1 reflector.go:140] pkg/mod/k8s.io/client-
go@v0.26.5/tools/cache/reflector.go:169: Failed to watch *v1beta1.VaultConnection: failed
 to list *v1beta1.VaultConnection: request to convert CR from an invalid group/version: secrets.hashicorp.com/v1alpha1
```

The issue is that the old VaultConnection v1alpha1 object was left behind but the CRD to support it no longer exists. To fix I had to remove v1beta1 connections, delete the CRDS, then reinstall "0.1.0-beta" so I could view and remove the original VaultConnection.

It seems like the old versions either need to be upgraded in future releases or documentation should state to remove all objects prior to upgrading. Thanks

**Comment by reedjosh** [comment]
Yeah, that wasn't too fun... : /

I also just went through this.

I use ArgoCD to deploy, and kept seen the chart fail to fully sync.

This project needs to either

1). Please please please announce the API change in bold everywhere as something that will require a full removal and replacement of VSO.

2). Leave the v1alpha1 CRDs in the config manifests so that both API versions can be installed at the same time. Of course in this case the project should also provide v1alpha1 -> v1beta1 upgrade webhooks.

I suppose 1). would be fine, but 2). is the general solution for CRD updates in an operator.

I guess sem-ver and all maybe I should have guessed this would smash everything? IDK

**Comment by reedjosh** [comment]
For anybody else in this pickle. (I force uninstalled the CRDs, but accidentally left a `vaultconnection` behind)

You can apply a CRD definition containing both version. Here is an example of what I did for `vaultconnections`


``` yaml
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: vaultconnections.secrets.hashicorp.com
spec:
  group: secrets.hashicorp.com
  names:
    kind: VaultConnection
    listKind: VaultConnectionList
    plural: vaultconnections
    singular: vaultconnection
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VaultConnection is the Schema for the vaultconnections API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VaultConnectionSpec defines the desired state of VaultConnection
            properties:
              address:
                description: Address of the Vault server
                type: string
              caCertSecretRef:
                description: CACertSecretRef containing the trusted PEM encoded CA
                  certificate chain.
                type: string
              headers:
                additionalProperties:
                  type: string
                description: Headers to be included in all Vault requests.
                type: object
              skipTLSVerify:
                description: SkipTLSVerify for TLS connections.
                type: boolean
              tlsServerName:
                description: TLSServerName to use as the SNI host for TLS connections.
                type: string
            required:
            - address
            type: object
          status:
            description: VaultConnectionStatus defines the observed state of VaultConnection
            properties:
              valid:
                description: Valid auth mechanism.
                type: boolean
            required:
            - valid
            type: object
        type: object
    served: false
    storage: false
    subresources:
      status: {}
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: VaultConnection is the Schema for the vaultconnections API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VaultConnectionSpec defines the desired state of VaultConnection
            properties:
              address:
                description: Address of the Vault server
                type: string
              caCertSecretRef:
                description: CACertSecretRef is the name of a Kubernetes secret containing
                  the trusted PEM encoded CA certificate chain as `ca.crt`.
                type: string
              headers:
                additionalProperties:
                  type: string
                description: Headers to be included in all Vault requests.
                type: object
              skipTLSVerify:
                description: SkipTLSVerify for TLS connections.
                type: boolean
              tlsServerName:
                description: TLSServerName to use as the SNI host for TLS connections.
                type: string
            required:
            - address
            type: object
          status:
            description: VaultConnectionStatus defines the observed state of VaultConnection
            properties:
              valid:
                description: Valid auth mechanism.
                type: boolean
            required:
            - valid
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```

This won't upgrade what's already there, but will at least allow you to manually access the abandoned v1alpha1 CRs.

Ideally an upgrade webhook would be supplied. : )
