### ISSUE TITLE
Secret is created successfully but logs indicate otherwise

### ISSUE THREAD

**Issue by wokalski** [hashicorp/vault-secrets-operator#286]
**Describe the bug**

I create a secret using VaultAuth, and VaultStaticSecret CRDs. It's created successfully when I run it for the first time but then logs indicate that something is going wrong:

```
2023-07-15 12:41:27 | 2023-07-15T10:41:27Z	DEBUG	events	Secret sync not required	{"type": "Normal", "object": {"kind":"VaultStaticSecret","namespace":"dialo","name":"caddie-test2-secret","uid":"dc09f4b6-d393-4804-8552-4eebb7c2234b","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"206261536"}, "reason": "SecretSync"}
-- | --
  |   | 2023-07-15 12:41:02 | 2023-07-15T10:41:02Z	DEBUG	events	Secret sync not required	{"type": "Normal", "object": {"kind":"VaultStaticSecret","namespace":"dialo","name":"caddie-test2-secret","uid":"dc09f4b6-d393-4804-8552-4eebb7c2234b","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"206261536"}, "reason": "SecretSync"}
  |   | 2023-07-15 12:40:36 | 2023-07-15T10:40:36Z	DEBUG	events	Vault secret was empty, mount kv, path caddie	{"type": "Warning", "object": {"kind":"VaultStaticSecret","namespace":"dialo","name":"caddie-test2-secret","uid":"dc09f4b6-d393-4804-8552-4eebb7c2234b","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"206261536"}, "reason": "VaultClientError"}
  |   | 2023-07-15 12:40:36 | /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
  |   | 2023-07-15 12:40:36 | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
  |   | 2023-07-15 12:40:36 | /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
  |   | 2023-07-15 12:40:36 | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
  |   | 2023-07-15 12:40:36 | /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323
  |   | 2023-07-15 12:40:36 | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
  |   | 2023-07-15 12:40:36 | /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122
  |   | 2023-07-15 12:40:36 | sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
  |   | 2023-07-15 12:40:36 | /home/runner/work/vault-secrets-operator/vault-secrets-operator/controllers/vaultstaticsecret_controller.go:115
  |   | 2023-07-15 12:40:36 | github.com/hashicorp/vault-secrets-operator/controllers.(*VaultStaticSecretReconciler).Reconcile
  |   | 2023-07-15 12:40:36 | 2023-07-15T10:40:36Z	ERROR	empty Vault secret	{"controller": "vaultstaticsecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultStaticSecret", "VaultStaticSecret": {"name":"caddie-test2-secret","namespace":"dialo"}, "namespace": "dialo", "name": "caddie-test2-secret", "reconcileID": "9e1bf3a5-2bfd-4316-a5c4-3a8dcc8cd94d", "mount": "kv", "path": "caddie"}
```

Notice error "empty Vault secret". However couple of minutes earlier the secret has been created and I can verify it is correct:
```
DEBUG	events	Secret synced	{"type": "Normal", "object": {"kind":"VaultStaticSecret","namespace":"dialo","name":"caddie-test2-secret","uid":"dc09f4b6-d393-4804-8552-4eebb7c2234b","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"206261499"}, "reason": "SecretSynced"}
```

**To Reproduce**
1. it happens to me every time I create vaultauth and vaultstaticsecret in my case.

Application deployment:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: caddie-test2-secret-auth
  namespace: dialo
spec:
  kubernetes:
    role: caddie
    serviceAccount: caddie
    tokenExpirationSeconds: 600
  method: kubernetes
  mount: kubernetes
---
kind: VaultStaticSecret
metadata:
  name: caddie-test2-secret
  namespace: dialo
spec:
  destination:
    create: true
    name: caddie-test2-secret
  hmacSecretData: true
  mount: kv
  path: caddie
  refreshAfter: 30s
  type: kv-v2
  vaultAuthRef: caddie-test2-secret-auth
```

values.yaml:

```
defaultVaultConnection: {
  enabled: true,
  address: "http://vault.vault.svc.cluster.local:8200",
}
```

**Expected behavior**
The secret is created correctly so I'd expect not to see any errors.

**Environment**
* Kubernetes version: v1.23
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): k3s
  * Other configuration options or runtime services (istio, etc.): n/a
* vault-secrets-operator version: 0.1.0
