### ISSUE TITLE
Instance Metadata Creds are overriding the IRSA Config

### ISSUE THREAD

**Issue by abebars** [hashicorp/vault-secrets-operator#290]
**Describe the bug**
Despite providing the IRSA configuration to the `VaultAuth` CRD, the creds retrieved for the `VaultStatucSecret` are the instance metadata instead of the IRSA Creds.

**To Reproduce**
1. Deploy the following CRDs
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: vault-operator-test  
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/eks-irsa-role
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: vault-operator-test  
  name: vault-operator-test  
spec:
  address: 127.0.0.1:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: vault-operator-test  
  name: vault-operator-test  
spec:
  vaultConnectionRef: vault-operator-test  
  method: aws
  aws:
    role: eks-cluster-irsa-dev
    region: us-east-1
    irsaServiceAccount: default
    sessionName: test-default

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: vault-operator-test
  name: vault-operator-test
spec:
  vaultAuthRef: vault-operator-test
  mount: kvv2
  type: kv-v2
  path: test/versioned/dev/test
  version: 2
  refreshAfter: 60s
  destination:
    create: true
    name: vault-operator-test
```
2. See error (vault-secrets-operator logs, application logs, etc.)
```
* IAM Principal "arn:aws:sts::1234567890:assumed-role/eks-node-group/i-*********" does not belong to the role "eks-cluster-irsa-dev"	{"type": "Warning", "object": {"kind":"VaultStaticSecret","namespace":"vault-operator-test","name":"vault-operator-test","uid":"1da539b5-e3df-42d7-9b9e-a11474314eef","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"690845005"}, "reason": "VaultClientConfigError"}
```

**Expected behavior**
If the IRSA config is supplied, I would expect the Creds generation to be using it and fail if there is an issue to get the creds with IRSA, Instead of falling back to Instance Metadata.
**Environment**
* Kubernetes version: 
  * EKS 1.23
* vault-secrets-operator version: 
  * v0.1.0
