### ISSUE TITLE
GCP "private_key_data" not decoded before write to k8s secrets

### ISSUE THREAD

**Issue by duong-se** [hashicorp/vault-secrets-operator#332]
**Describe the bug**
GCP "private_key_data" not decoded before write to k8s secrets

**To Reproduce**
1. Deploy connection. 
```
# Vault connection
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: vso-example
  name: example
spec:
  # address to the Vault server.
  address: http://vault.vault.svc.cluster.local:8200
```
2. Deploy vault auth
```
# Vault Auth
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: vso-example
  name: example
spec:
  vaultConnectionRef: example
  # Method to use when authenticating to Vault.
  method: kubernetes
  # Mount to use when authenticating to auth method.
  mount: kubernetes
  kubernetes:
    role: demo
    serviceAccount: default
```
 3. Deploy vault dynamic secrets
```
 apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  namespace: vso-example
  name: example
spec:
  vaultAuthRef: example
  mount: gcp
  path: key/demo-role
  destination:
    create: true
    name: dynamic1
```

**Result**
Secret will created as below
```
"key_algorithm":    "KEY_ALG_RSA_2048",
"key_type":         "TYPE_GOOGLE_CREDENTIALS_FILE",
"private_key_data": "eyJ0eXBlIjoic2VydmljZV9hY2NvdW50IiwicHJvamVjdF9pZCI6IlBST0pFQ1RfSUQiLCJwcml2YXRlX2tleV9pZCI6IktFWV9JRCIsInByaXZhdGVfa2V5IjoiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5QUklWQVRFX0tFWVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwiY2xpZW50X2VtYWlsIjoiU0VSVklDRV9BQ0NPVU5UX0VNQUlMIiwiY2xpZW50X2lkIjoiQ0xJRU5UX0lEIiwiYXV0aF91cmkiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsInRva2VuX3VyaSI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi90b2tlbiIsImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsImNsaWVudF94NTA5X2NlcnRfdXJsIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9TRVJWSUNFX0FDQ09VTlRfRU1BSUwifQ==",
```

**Expected behavior**
So the expect behavior the secret should return this value instead of value below
```
"_raw":             "{\"key_algorithm\":\"KEY_ALG_RSA_2048\",\"key_type\":\"TYPE_GOOGLE_CREDENTIALS_FILE\",\"private_key_data\":\"eyJ0eXBlIjoic2VydmljZV9hY2NvdW50IiwicHJvamVjdF9pZCI6IlBST0pFQ1RfSUQiLCJwcml2YXRlX2tleV9pZCI6IktFWV9JRCIsInByaXZhdGVfa2V5IjoiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5QUklWQVRFX0tFWVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwiY2xpZW50X2VtYWlsIjoiU0VSVklDRV9BQ0NPVU5UX0VNQUlMIiwiY2xpZW50X2lkIjoiQ0xJRU5UX0lEIiwiYXV0aF91cmkiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsInRva2VuX3VyaSI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi90b2tlbiIsImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsImNsaWVudF94NTA5X2NlcnRfdXJsIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9TRVJWSUNFX0FDQ09VTlRfRU1BSUwifQ==\"}",
"key_algorithm":    "KEY_ALG_RSA_2048",
"key_type":         "TYPE_GOOGLE_CREDENTIALS_FILE",
"private_key_data": `{"type":"service_account","project_id":"PROJECT_ID","private_key_id":"KEY_ID","private_key":"-----BEGIN PRIVATE KEY-----\nPRIVATE_KEY\n-----END PRIVATE KEY-----\n","client_email":"SERVICE_ACCOUNT_EMAIL","client_id":"CLIENT_ID","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/SERVICE_ACCOUNT_EMAIL"}`,
```

**Environment**
* Kubernetes version: 1.25.8-gke.1000
* vault-secrets-operator version: 0.1.0
**Additional context**
None
