### ISSUE TITLE
Cannot overwrite existing secrets 

### ISSUE THREAD

**Issue by nia-potato** [hashicorp/vault-secrets-operator#337]
**Describe the bug**
After deploying vso to kubernetes cluster with kube auth, new static secrets are working just fine, however when dealing with existing secrets, and trying to use vso to manage the existing secret with the same name i am getting the following errors:

```
invalid owner label, key=app.kubernetes.io/name, present=false
invalid owner label, key=app.kubernetes.io/managed-by, present=false
secret default/oauth-client-secret has no ownerReferences
not the owner of the destination Secret default/oauth-client-secret     {"type": "Warning", "object": {"kind":"VaultStaticSecret","namespace":"default","name":"oauth-client-secret","uid":"f5ea7c7e-ff85-4274-acd4-4a1c7d53c77","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"37293181"}, "reason": "SecretSyncError"}
```

**To Reproduce**
to deploy VSO (vso excerpt):

```
resource "helm_release" "vault-secrets-operator" {
  depends_on      = [kubernetes_namespace.ns] // Add this line
  wait            = true
  wait_for_jobs   = true
  name            = "vault-secrets-operator"
  repository      = "https://helm.releases.hashicorp.com"
  chart           = "vault-secrets-operator"
  namespace       = kubernetes_namespace.ns.metadata.0.name

  values = [templatefile("${path.module}/values.yaml.tpl", {
    vault_kube_auth_role = vault_kubernetes_auth_backend_role.vso.role_name
    namespace            = var.namespace
    vault_ip_address     = local.vault_ip_address
    auth_mount_path      = "${var.gcp_project}/${var.cluster_name}"
    gke_audience         = local.gke_audience
  })]
}

resource "vault_auth_backend" "kubernetes" {
  type = "kubernetes"
  path = "${var.gcp_project}/${var.cluster_name}" // mount path
}

resource "kubernetes_secret_v1" "sa" {
  depends_on                     = [helm_release.vault-secrets-operator]
  wait_for_service_account_token = true
  metadata {
    name      = "vault-sa"
    namespace = var.namespace
    annotations = {
      "kubernetes.io/service-account.name" = "vault-secrets-operator-controller-manager"
    }
  }
  type = "kubernetes.io/service-account-token"
}

data "kubernetes_config_map_v1" "ca" {
  metadata {
    name      = "kube-root-ca.crt"
    namespace = "kube-public"
  }
}

resource "vault_kubernetes_auth_backend_config" "kubernetes" {
  backend                = vault_auth_backend.kubernetes.path
  kubernetes_host        = "https://${data.google_container_cluster.primary.endpoint}"
  kubernetes_ca_cert     = data.kubernetes_config_map_v1.ca.data["ca.crt"]
  token_reviewer_jwt     = kubernetes_secret_v1.sa.data["token"]
  disable_iss_validation = true
  disable_local_ca_jwt   = true
  issuer                 = "https://container.googleapis.com/v1/projects/${var.gcp_project}/locations/${var.region}/clusters/${var.cluster_name}"
}

resource "vault_kubernetes_auth_backend_role" "vso" {
  backend                          = vault_auth_backend.kubernetes.path
  role_name                        = "vso"
  bound_service_account_names      = ["default"]
  bound_service_account_namespaces = ["*"]
  token_ttl                        = 3600
  token_policies                   = ["default", vault_policy.vso.name]
  audience                         = local.gke_audience
}

resource "vault_policy" "vso" {
  name   = "vso"
  policy = file("${path.module}/policies/vso.hcl") // read policy from file
}
```

Check the existing secret
λ › k get secrets                                                                                                                                   
NAME                       TYPE     DATA   AGE
oauth-client-secret        Opaque   2      19h

To write a secret with the same name so that it can be vault managed. 

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: test-vso2
  name: oauth-client-secret
spec:
  mount: secret #path of your secret engine, it could also be user/ or secret/
  type: kv-v2 #type of secret engine
  path: gcp-project/cluster-name/namespace/oauth-client-secret
  refreshAfter: 60s
  destination:
    create: true
    name: oauth-client-secret #what you want the display name to be in kubernetes secret.
    
   
   ```
   
   After applying that i am getting this error:
   ```
invalid owner label, key=app.kubernetes.io/name, present=false
invalid owner label, key=app.kubernetes.io/managed-by, present=false
secret default/oauth-client-secret has no ownerReferences
not the owner of the destination Secret default/oauth-client-secret     {"type": "Warning", "object": {"kind":"VaultStaticSecret","namespace":"default","name":"oauth-client-secret","uid":"f5ea7c7e-ff85-4274-acd4-4a1c7d53c77","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"37293181"}, "reason": "SecretSyncError"}
```

**Expected behavior**
it should be overwritten by vso, and the secrets ttl should refresh and be now managed by vso. 

**Environment**
* Kubernetes version: 
  * GKE 1.24 
* vault-secrets-operator version: 0.1.0

**Additional context**
I am trying to do a secrets migration, and i believe vso need to be able to overwrite existing secrets with the same name. i am doing this via automation, and would not like to delete secrets then overwrite them. it could cause down time.

**Comment by tvoran** [comment]
Hi @nia-potato, have you tried omitting or setting `create: false` in the VaultStaticSecret's `spec.destination`? The destination fields are described a bit here: https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#destination

**Comment by nia-potato** [comment]
Thank you @tvoran, I can get it to work with with `create: false` but i am under the use case of:  if the user deletes the kube secret in the future, wouldn't that mean it will not be re-created and synced due to `create: false` if they want to have a deleted secret re-synced and created, they would need to have `create: true` right? 

I've been trying my luck to solve the owner ship issue by adding annotations in the `spec.destination.annotations` with 

```yaml
app.kubernetes.io/name: vault-secrets-operator
app.kubernetes.io/managed-by: Helm
```

but had no avail.

**Comment by nia-potato** [comment]
@tvoran sry to ping u again, but we are being blocked by this during our secrets migration to vault, if we need to delete existing secrets, then recreate them via vso, we might introduce downtime to our clusters, so i would really hope we can find a solution to have `create: true` to preserve the use case of auto-create secret if deleted in the future after vso manages it, and not needing to delete the existing secret prior to the cutover.

**Comment by tvoran** [comment]
Hi @nia-potato, the operator doesn't currently support the scenario you're describing; it's pretty strict about either owning the k8s secret or only updating an existing one. When `create: true`, the operator creates the k8s secret with these metadata items (and uses them to verify ownership during updates):

```yaml
metadata:
  labels:
    app.kubernetes.io/component: secret-sync
    app.kubernetes.io/managed-by: hashicorp-vso
    app.kubernetes.io/name: vault-secrets-operator
  ownerReferences:
  - apiVersion: secrets.hashicorp.com/v1beta1
    kind: VaultStaticSecret
    name: oauth-client-secret
    uid: <uid of the VaultStaticSecret>

```

The owner reference in particular means that when the VaultStaticSecret is deleted, the k8s secret is also deleted by kubernetes' garbage collection, to keep Vault secrets from outliving their intended usage and leaking. When `create: false`, the operator will only update an existing k8s secret.

If `create: true` would also take over ownership of an existing k8s secret, would you expect that k8s secret to be deleted when the corresponding VaultStaticSecret is deleted? (Just trying to get a better idea of your use-case.)
