### ISSUE TITLE
[VaultStaticSecret] No updates in k8s secret when modifying the K/V pair in Vault

### ISSUE THREAD

**Issue by jpigree** [hashicorp/vault-secrets-operator#347]
**Describe the bug**
I try to sync a key/value from a kv2 secret store into a Kubernetes secret using a VaultStaticSecret CRD.
The Operator successfully creates the secret however it won't sync it into Kubernetes when I update it in Vault.
 
**To Reproduce**
1. Deploy a Vault instance and unseal it
2. Create a KV2 secret engine mounted on test
3. Create the key "project/app"
```
vault kv put --mount=test project/app '{"test": "test"}'
```

4. Create an AppRole (id, secret) and a policy which enables the appRole to have a Read Only access to the KV2 test 
7. Deploy the vault-secrets-operator with default values file
```
helm install hashicorp/vault-secrets-operator
```
9. Create VaultConnection
```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  finalizers:
  - vaultconnection.secrets.hashicorp.com/finalizer
  name: default
  namespace: vso-system
spec:
  address: https://<VAULT_FQDN>:8200
  skipTLSVerify: true
status:
  valid: true
```

10. Create VaultAuth
```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  finalizers:
  - vaultauth.secrets.hashicorp.com/finalizer
  name: default
  namespace: vso-system
spec:
  appRole:
    roleId: <APPROLE_ID>
    secretRef: auth-secret
  method: appRole
  mount: approle
  namespace: vso-system
  vaultConnectionRef: default
status:
  error: ""
  valid: true
```

12. Create a VaultStaticSecret in another namespace pointing to the secret  in the kv store
```
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: project-app-test-vso
data:
  id: <Hashed APPROLE_SECRET>
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: test-secrets
  namespace: project-app-test-vso
spec:
  vaultAuthRef: vso-system/default
  mount: test
  type: kv-v2
  path: project/app
  hmacSecretData: true
  version: 2
  refreshAfter: 60s
  destination:
    create: true
    name: test-secrets
```

13. Do a kubectl describe of the VaultStaticSecret
```
[...]
Events:
  Type    Reason        Age                From               Message
  ----    ------        ----               ----               -------
  Normal  SecretSynced  15m                VaultStaticSecret  Secret synced>
``` 
 **It worked and the secret was created.** 

15.Now to modify the content of the KV pair.
```
vault kv put --mount=test project/app '{"test": "test1"}'
```

17. Do a kubectl describe of the VaultStaticSecret
```
[...]
Events:
  Type    Reason        Age                 From               Message
  ----    ------        ----                ----               -------
  Normal  SecretSynced  18m                 VaultStaticSecret  Secret synced
  Normal  SecretSync    41s (x21 over 17m)  VaultStaticSecret  Secret sync not required
```

**The VSS says that the secret does not need to be synced. The secret is not synced. 
Even when I recreate the VSS/restart the VSO pod/reinstall the VSO chart, it will still use the old version of the key/value pair.** 

**Expected behavior**
The secret should be updated when I update the secret inside Vault.

**Environment**
* Kubernetes version: v1.23
  * Distribution:  k0s
* vault-secrets-operator version: 0.2.0

**Additional context**
Even with debug logs activated, I can't see a useful info in the operator logs:
```
2023-08-31T18:40:41Z    DEBUG   events  Secret synced   {"type": "Normal", "object": {"kind":"VaultStaticSecret","namespace":"project-app--test-vso","name":"test-secrets","uid":"26850132-17de-473a-9e9e-e036c06a
4d05","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"128634869"}, "reason": "SecretSynced"}
2023-08-31T18:41:34Z    DEBUG   events  Secret sync not required        {"type": "Normal", "object": {"kind":"VaultStaticSecret","namespace":"project-app-test-vso","name":"test-secrets","uid":"26850132-17de-47
3a-9e9e-e036c06a4d05","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"128634872"}, "reason": "SecretSync"}
2023-08-31T18:42:25Z    DEBUG   events  Secret sync not required        {"type": "Normal", "object": {"kind":"VaultStaticSecret","namespace":"project-app-test-vso","name":"test-secrets","uid":"26850132-17de-47
3a-9e9e-e036c06a4d05","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"128634872"}, "reason": "SecretSync"}
[...]
```
Does the VSO actually caches the data from Vault?
