### ISSUE TITLE
Rotation of secrets fails due to "Secret xxx not found"

### ISSUE THREAD

**Issue by andrejvanderzee** [hashicorp/vault-secrets-operator#364]
Rotation of secrets for `hashicorp/vault-secrets-operator:0.2.0` often fails showing the following errors in the logs: 

```
2023-09-18T07:21:46Z	INFO	Got deletion timestamp	{"controller": "vaultdynamicsecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultDynamicSecret", "VaultDynamicSecret": {"name":"database-rds","namespace":"infra"}, "namespace": "infra", "name": "database-rds", "reconcileID": "aa98f8e7-4f86-4c1a-a1bd-e96bab0f13d5", "obj": {"apiVersion": "secrets.hashicorp.com/v1beta1", "kind": "VaultDynamicSecret", "namespace": "infra", "name": "database-rds"}}
2023-09-18T07:21:46Z	INFO	Revoking lease for credential 	{"controller": "vaultdynamicsecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultDynamicSecret", "VaultDynamicSecret": {"name":"database-rds","namespace":"infra"}, "namespace": "infra", "name": "database-rds", "reconcileID": "aa98f8e7-4f86-4c1a-a1bd-e96bab0f13d5", "id": "management/rds/creds/eks-service-database-owner/Dy8esyd5is0VlN7vNT3hfsAc"}
{"level":"info","ts":"2023-09-18T07:21:46Z","logger":"clientCacheFactory","msg":"Setting up Vault Client for storage encryption","persist":true,"enforceEncryption":true,"cacheKey":"kubernetes-0ee175333e92d8a3e710da"}
2023-09-18T07:21:46Z	ERROR	cachingClientFactory	Failed to restore client from storage	{"controller": "vaultdynamicsecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultDynamicSecret", "VaultDynamicSecret": {"name":"database-rds","namespace":"infra"}, "namespace": "infra", "name": "database-rds", "reconcileID": "aa98f8e7-4f86-4c1a-a1bd-e96bab0f13d5", "error": "Secret \"vso-cc-kubernetes-3e6be83294f886a892cf48\" not found"}
github.com/hashicorp/vault-secrets-operator/internal/vault.(*cachingClientFactory).Get
	/home/runner/work/vault-secrets-operator/vault-secrets-operator/internal/vault/client_factory.go:309
github.com/hashicorp/vault-secrets-operator/controllers.(*VaultDynamicSecretReconciler).revokeLease
	/home/runner/work/vault-secrets-operator/vault-secrets-operator/controllers/vaultdynamicsecret_controller.go:469
github.com/hashicorp/vault-secrets-operator/controllers.(*VaultDynamicSecretReconciler).handleDeletion
	/home/runner/work/vault-secrets-operator/vault-secrets-operator/controllers/vaultdynamicsecret_controller.go:443
github.com/hashicorp/vault-secrets-operator/controllers.(*VaultDynamicSecretReconciler).Reconcile
	/home/runner/work/vault-secrets-operator/vault-secrets-operator/controllers/vaultdynamicsecret_controller.go:103
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
```
CachingClientFactory is setup with encryption: 

```
{"level":"info","ts":"2023-09-17T10:57:53Z","logger":"initCachingClientFactory","msg":"Initializing the CachingClientFactory"}
{"level":"info","ts":"2023-09-17T10:57:53Z","logger":"clientCacheFactory","msg":"Setting up Vault Client for storage encryption","persist":true,"enforceEncryption":true,"cacheKey":""}
2023-09-17T10:57:54Z	INFO	setup	Starting manager	{"clientCachePersistenceModel": "direct-encrypted", "clientCacheSize": 10000}
```

This is the VaultDynamicSecret:

```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  namespace: infra
  name: database-rds
spec:
  vaultAuthRef: keycloak
  mount: management/rds
  path: creds/eks-service-database-owner
  revoke: true
  destination:
    create: true
    name: database-rds
  rolloutRestartTargets:
  - kind: StatefulSet
    name: database-mirror
```

Am I overseeing something?

**Comment by andrejvanderzee** [comment]
We still regularly get secrets that are not renewed. We see these errors in logs: 

```
{"level":"info","ts":"2023-12-07T08:28:36Z","logger":"clientCacheFactory","msg":"Setting up Vault Client for storage encryption","persist":true,"enforceEncryption":true,"cacheKey":"kubernetes-80b6c4085fce0d679d7ca1"}
2023-12-07T08:28:36Z	ERROR	cachingClientFactory	Failed to restore client from storage	{"controller": "vaultdynamicsecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultDynamicSecret", "VaultDynamicSecret": {"name":"prometheus-postgres-exporter-rds","namespace":"infra"}, "namespace": "infra", "name": "prometheus-postgres-exporter-rds", "reconcileID": "3f7ab8a7-b9b1-4a67-b3db-a72e85cced6a", "error": "expected Client for storage encryption not found in the cache, cacheKey=kubernetes-80b6c4085fce0d679d7ca1"}
github.com/hashicorp/vault-secrets-operator/internal/vault.(*cachingClientFactory).Get
	/home/runner/work/vault-secrets-operator/vault-secrets-operator/internal/vault/client_factory.go:370
github.com/hashicorp/vault-secrets-operator/controllers.(*VaultDynamicSecretReconciler).revokeLease
	/home/runner/work/vault-secrets-operator/vault-secrets-operator/controllers/vaultdynamicsecret_controller.go:475
github.com/hashicorp/vault-secrets-operator/controllers.(*VaultDynamicSecretReconciler).handleDeletion
	/home/runner/work/vault-secrets-operator/vault-secrets-operator/controllers/vaultdynamicsecret_controller.go:449
github.com/hashicorp/vault-secrets-operator/controllers.(*VaultDynamicSecretReconciler).Reconcile
	/home/runner/work/vault-secrets-operator/vault-secrets-operator/controllers/vaultdynamicsecret_controller.go:110
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227

```

**Comment by andrejvanderzee** [comment]
@benashz Some extra information, we have migrated from `vault-agent-injector` with sidecars but we have occasional serious problems with renewal of VDS. It doesnt happen every time and when I set the TTLs very low I can see that leases are renewed and when the TTL is truncated because `max_ttl` comes into play, the rollout restart is successfully executed.

But, under certain unknown conditions it fails and the kubernetes secret is not recreated (the `creationTimestamp` of the Kubernetes secret is way past `max_ttl`). Here the relevant Vault configuration: 

We are on version `0.4.2`.

```
$ vault read auth/shared/eks/role/altersis-perfana-grafana
Key                                 Value
---                                 -----
alias_name_source                   serviceaccount_uid
bound_service_account_names         [perfana-grafana]
bound_service_account_namespaces    [altersis]
token_bound_cidrs                   []
token_explicit_max_ttl              0s
token_max_ttl                       0s
token_no_default_policy             false
token_num_uses                      0
token_period                        0s
token_policies                      [shared-eks-service-altersis-perfana-grafana]
token_ttl                           24h
token_type                          default

$ vault read shared/rds/roles/eks-service-altersis-grafana-owner
Key                      Value
---                      -----
creation_statements      [CREATE ROLE "{{name}}" WITH LOGIN INHERIT ENCRYPTED PASSWORD '{{password}}' ALTER ROLE "{{name}}" SET search_path = altersis, public GRANT altersis_grafana_owner TO "{{name}}"]
credential_type          password
db_name                  postgres
default_ttl              336h
max_ttl                  336h
renew_statements         []
revocation_statements    [REVOKE altersis_grafana_owner FROM "{{name}}" DROP ROLE "{{name}}"]
rollback_statements      []
```

And here the VSO config: 

```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: grafana
  namespace: altersis
spec:
  kubernetes:
    role: altersis-grafana
    serviceAccount: grafana
    tokenExpirationSeconds: 600
  method: kubernetes
  mount: shared/eks  
 

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  generation: 1
  name: grafana-rds
  namespace: altersis
spec:
  destination:
    create: true
    name: grafana-vso-rds
  mount: shared/rds
  path: creds/eks-service-altersis-grafana-owner
  renewalPercent: 67
  revoke: true
  rolloutRestartTargets:
  - kind: Deployment
    name: grafana
  vaultAuthRef: grafana
```
