### ISSUE TITLE
HCP Vault Secret with Vault Secret Operator failed to verify certificate

### ISSUE THREAD

**Issue by bizalu** [hashicorp/vault-secrets-operator#412]
**Describe the bug**
I try to synchronise secret from HCP Vault Secret and my kubernetes cluster (openshift 4.13) with the Vault Secret Operator (v0.3.2).
I create my HCPAuth and HCPVaultSecretsApp and I’ve got error on my logs from vault-secrets-operator-controller-manager pod.

**To Reproduce**
1. Deploy VSO operator from Redhat certified operator catalog
2. Create a secret with my clienID and clienSecret (service principal with contributor role)
3. Create a HCPAuth with my organizationID and projectID
4. Create a HCPVaultSecretsApp 
5. See error ( vault-secrets-operator-controller-manager)

HCPAuth :
```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: hcp-media
  namespace: openshift-vault-operator
spec:
  method: servicePrincipal
  organizationID: xxxx
  projectID: xxx
  servicePrincipal:
    secretRef: hcpvaultmedia
```

HCPVaultSecretsApp :
```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: media-test
  namespace: openshift-vault-operator
spec:
  appName: media
  destination:
    create: true
    name: test
    type: Opaque
  hcpAuthRef: hcp-media
  refreshAfter: 600s
```

Log from vault-secrets-operator-controller-manager pod :
```log
2023-10-06T05:00:32Z ERROR Get App Secret {"controller": "hcpvaultsecretsapp", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "HCPVaultSecretsApp", "HCPVaultSecretsApp": {"name":"xxx","namespace":"xxx"}, "namespace": "xxx", "name": "xxx", "reconcileID": "xxx", "appName": "xxx", "error": "Get \"https://api.cloud.hashicorp.com:443/secrets/2023-06-13/organizations/xxx/apps/media/open\": Post \"https://auth.idp.hashicorp.com/oauth2/token\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
```

**Environment**
* Kubernetes version: Openshift 4.13.14
* vault-secrets-operator version: 0.3.2
