### ISSUE TITLE
VaultStaticSecret syncs secret from Vault every ~8 minutes even though refreshAfter parameter is set as '2h'

### ISSUE THREAD

**Issue by DzmitrySurovets** [hashicorp/vault-secrets-operator#427]
**Describe the bug**
VaultStaticSecret syncs secret from Vault every ~8 minutes even though refreshAfter parameter is set as '2h' or more.

**To Reproduce**
1. Create a vault static secret with spec.refreshAfter: "2h"
2. Describe the vault static secret:
`kubectl describe vaultstaticsecrets.secrets.hashicorp.com {name_of_the_vaultstaticsecret}`
4. See that secretSync runs every ~7-8 minutes in the Events
```
$ kubectl describe vaultstaticsecrets.secrets.hashicorp.com webapp-temp-secret
Name:         webapp-temp-secret
Namespace:    example-vault-operator
Labels:       <none>
Annotations:  <none>
API Version:  secrets.hashicorp.com/v1beta1
Kind:         VaultStaticSecret
Metadata:
  Creation Timestamp:  2023-10-25T10:47:30Z
  Generation:          1
  Resource Version:    332988
  UID:                 4df58d6f-1446-4b70-89bb-91ccf1ce94af
Spec:
  Destination:
    Create:          true
    Name:            webapp-temp-secret
  Hmac Secret Data:  true
  Mount:             infrastore
  Path:              webapp-temp-secret
  Refresh After:     2h
  Type:              kv-v2
  Vault Auth Ref:    ns-system/static-auth
Status:
  Secret MAC:  ####################
Events:
  Type    Reason        Age    From               Message
  ----    ------        ----   ----               -------
  Normal  SecretSynced  30m    VaultStaticSecret  Secret synced
  Normal  SecretSync    23m    VaultStaticSecret  Secret sync not required
  Normal  SecretSync    16m    VaultStaticSecret  Secret sync not required
  Normal  SecretSync    8m41s  VaultStaticSecret  Secret sync not required
  Normal  SecretSync    81s    VaultStaticSecret  Secret sync not required
```

VaultStaticSecret manifest:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webapp-temp-secret
  namespace: example-vault-operator
spec:
  type: kv-v2
  # mount path
  mount: infrastore
  # path of the secret
  path: webapp-temp-secret
  # dest k8s secret
  destination:
    name: webapp-temp-secret
    create: true # Set to false if k8s secret already exists
  # static secret refresh interval
  refreshAfter: "2h"
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: ns-system/static-auth
```

**Expected behavior**
The secret must be synced every 2 hours.

**Actual behavior**
The secret syncs every ~8 minutes.

**Environment**
* Kubernetes version: 
 EKS 1.25
* vault-secrets-operator version:
0.3.4
