### ISSUE TITLE
Create a possibility to specify which keys could be inside a kube secret

### ISSUE THREAD

**Issue by josiasnonato** [hashicorp/vault-secrets-operator#441]
Hi Team.

I can't find in Hashicorp docs some like this, because of this I am opening this issue.

I would like to specify which keys (fields) should be inside a secret of Kubernetes.

Today, a secret is created in kubernetes with all keys inside a vault path, but sometimes, it's no necessary, just some secrets is necessary.
So, I believe that should be exist something like this.

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: my-secret
  namespace: myapplication
spec:
  mount: kvv2
  type: kv-v2
  path: path/to/my/secret/in/vault
  keys:
  - username
  - password
  - config
  refreshAfter: 60s
  destination:
    create: true
    name: my-secret-in-kubernetes
```

Then, a Kuberentes secret will be:

```yaml
apiVersion: v1
data:
  password: YWRtaW4K
  username: YWRtaW4=
  config: YWRtaW4=
kind: Secret
metadata:
  name: my-secret-in-kubernetes
  namespace: myapplication
type: Opaque
```

This type of config, could help Sec department to monitor and teams to create secrets only with necessary keys, anymore.
