### ISSUE TITLE
Kubernetes auth method does not work with short lived tokens

### ISSUE THREAD

**Issue by stok1y** [hashicorp/vault-secrets-operator#462]
**Describe the bug**
I was set up short lived token for my pod [Specifying TTL and audience](https://developer.hashicorp.com/vault/docs/auth/jwt/oidc-providers/kubernetes#specifying-ttl-and-audience)
and didn't add audience to VaultAuth CR. When I try to get secret from Vault I got up an error:
"403 audiences in jwt are not allowed."
This error I saw in to VaultAuth Custom Resource. When I try to log in to Vault directly with short lived token from "test-pod" it work properly.
Example:
1. kubectl test-pod exec
2. cat /var/run/secrets/kubernetes.io/serviceaccount/token
3. copy token and logout
4. vault write auth/<path-to-jwt-backend>/login role=demo jwt=<from 3 line token>

**To Reproduce**
1. Set up AuthRole in Kubernetes
2. Apply k8s yaml manifest in below section
3. kubectl describe customresourcedefinitions.apiextensions.k8s.io vaultauths.secrets.hashicorp.com vso-test-auth
6. See error (vaultauths custom-resource)

Application deployment:

```bash
vault write auth/kubernetes/role/role1 \
   bound_service_account_names=nginx \
   bound_service_account_namespaces=default \
   policies=dev \
   audience=vault \
   ttl=1h
```

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-test-auth
spec:
  # required configuration
  # VaultConnectionRef of the corresponding VaultConnection CustomResource.
  # If no value is specified the Operator will default to the `default` VaultConnection,
  # configured in its own Kubernetes namespace.
  vaultConnectionRef: vault/default
  # Method to use when authenticating to Vault.
  method: kubernetes
  # Mount to use when authenticating to auth method.
  mount: kubernetes
  # optional configuration
  # Vault namespace where the auth backend is mounted (requires Vault Enterprise)
  namespace: default
  kubernetes:
    # role to use when authenticating to Vault
    role: default
    # ServiceAccount to use when authenticating to Vault
    # it is recommended to always provide a unique serviceAccount per Pod/application
    serviceAccount: nginx
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: default
  name: vso-test-vss
spec:
  # namespace: cluster1/tenant-1
  vaultAuthRef: vso-test-auth
  mount: secret
  type: kv-v2
  path: infra/test
  refreshAfter: 5s
  destination:
    create: true
    name: secret
---
apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: default
spec:
  serviceAccountName: nginx
  automountServiceAccountToken: false
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
      readOnly: true
    - name: custom-token
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  volumes:
  - name: secrets
    secret:
      secretName: secret
  - name: custom-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 600 # 10 minutes is the minimum TTL
          audience: vault        # Must match your JWT role's `bound_audiences`
      # The remaining sources are included to mimic the rest of the default
      # admission injected volume.
      - configMap:
          name: kube-root-ca.crt
          items:
          - key: ca.crt
            path: ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

**Expected behavior**
Possibility to get secrets with short lived token, without adding "audiences" to VaultAuth.

**Environment**
* Kubernetes version: 
  * cloud vendor (AKS):
  * Other configuration options or runtime services (istio, etc.):
* vault-secrets-operator version: 0.3.4
