### ISSUE TITLE
Kubernetes PKI secret not updating

### ISSUE THREAD

**Issue by bmaximuml** [hashicorp/vault-secrets-operator#465]
**Describe the bug**
I am using Terraform to deploy a VaultPKISecret resource linked to a kubernetes secret. When I update the VaultPKISecret to add additional alt names, these are reflected in the description of the resource. The operator then spits out logs saying it has synced the corresponding Kubernetes secret, however reading the secret shows its certificate to be unchanged, and not to include the new alt names.

**To Reproduce**
1. Deploy VaultPKISecret with a set of 5 alt names (as shows in terraform file below).
2. Update the resource to add an extra alt name (raise the range from `5` e.g. `7`).
3. Check VaultPKISecret to confirm it has added the alt names.
4. Check vault-operator logs to confirm it has synced the VaultPKISecret with the kubernetes secret
3. Check kubernetes secret to see it has not added the alt names.

Application deployment:

main.tf
```terraform
locals {
  cluster_name = "my-cluster"
  role_name    = "my_role"
  secret_name  = "${local.cluster_name}-cert-secret"
  hostnames = [for i in range(5) : "my-cluster-${i}.example.com"]
}

resource "kubernetes_namespace" "my_cluster" {
  metadata {
    name = local.cluster_name
  }
}

resource "kubernetes_service_account" "my_cluster" {
  metadata {
    name      = local.cluster_name
    namespace = kubernetes_namespace.my_cluster.metadata[0].name
  }
  automount_service_account_token = true
}

resource "kubectl_manifest" "vault_auth" {
  yaml_body = templatefile("vault_auth.tftpl", {
    auth_name            = local.cluster_name
    role_name            = local.role_name
    service_account_name = kubernetes_service_account.my_cluster.metadata[0].name
    namespace            = kubernetes_namespace.my_cluster.metadata[0].name

  })
  override_namespace = kubernetes_namespace.my_cluster.metadata[0].name
}

resource "kubectl_manifest" "vault_broker_cert" {
  yaml_body = templatefile("vault_broker_cert.tftpl", {
    auth_name   = local.cluster_name
    role_name   = local.role_name
    secret_name = local.secret_name
    common_name = local.cluster_name
    ttl         = "1d"
    alt_names   = local.hostnames
    ip_sans     = []
    other_sans  = []
    uri_sans    = []
    namespace   = kubernetes_namespace.my_cluster.metadata[0].name
  })
  override_namespace = kubernetes_namespace.my_cluster.metadata[0].name
}

module "vault" {
  source                         = "path/to/custom/vault/module"
  environment_name               = "dev"
  namespace_name                 = kubernetes_namespace.my_cluster.metadata[0].name
  service_account_name           = kubernetes_service_account.my_cluster.metadata[0].name
  allowed_domains                = concat([local.cluster_name], local.hostnames)
  organizational_unit            = "Max Levine ${local.cluster_name}"
  enable_pki_secret_backend_role = true
  role_name                      = local.role_name
  allow_ip_sans                  = true
  depends_on                     = [kubernetes_service_account.my_cluster]
}

```

vault_auth.tftpl
```yaml
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: ${auth_name}
  namespace: ${namespace}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: ${role_name}
    serviceAccount: ${service_account_name}
    audiences:
      - vault
```

vault_broker_cert.tftpl
```yaml
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: ${secret_name}
  namespace: ${namespace}
spec:
  vaultAuthRef: ${auth_name}
  mount: pki_d2_ecdsa
  role: ${role_name}
  commonName: ${common_name}
  format: pem
  expiryOffset: 1s
  ttl: ${ttl}
#  revoke: true
  clear: true
  %{~ if length(ip_sans) > 0 ~}
  ipSans:
    %{~ for san in ip_sans ~}
    - ${san}
    %{~ endfor ~}
  %{~ endif ~}
  %{~ if length(other_sans) > 0 ~}
  otherSans:
    %{~ for san in other_sans ~}
    - ${san}
    %{~ endfor ~}
  %{~ endif ~}
  %{~ if length(uri_sans) > 0 ~}
  uriSans:
    %{~ for san in uri_sans ~}
    - ${san}
    %{~ endfor ~}
  %{~ endif ~}
  %{~ if length(alt_names) > 0 ~}
  altNames:
    %{~ for alt_name in alt_names ~}
    - ${alt_name}
    %{~ endfor ~}
  %{~ endif ~}
  destination:
    create: true
    name: ${secret_name}
    type: kubernetes.io/tls
```

**Expected behavior**
The kubernetes secret to be rotated to include the new alt names

**Environment**
* Kubernetes version: v1.25.10
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): GKE
  * Other configuration options or runtime services (istio, etc.): external-dns
* vault-secrets-operator version: v0.4.0
