### ISSUE TITLE
In V0.4.0, VaultDynamicSeceret (Static Role) is not rolling update when rotation_schedule is reached

### ISSUE THREAD

**Issue by toasahi** [hashicorp/vault-secrets-operator#466]
**Describe the bug**
Vault Secrets Operator was upgraded from V0.3.4 to V0.4.0. The restart of the pod of applications using VaultDynamicSecret when the VSO manager pod is restarted was improved.
However, Deployment added to rolloutRestartTargets of VaultDyanamic Secret (Static Role) when the TTL of the RotationSchedule is reached is not rolling update.
I feel this is a bug, when I lowered the version to v0.3.4, the Deployment did rolling updates when the TTL of the RotationSchedule was reached. We hope this will be resolved in the future.

VaultDyanamic Secret(Static Role)

Application deployment:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-demo
  namespace: default
spec:
  allowStaticCreds: true
  # Mount path of the secrets backend
  mount: db

  # Path to the secret
  path: static-creds/postgres

  # Where to store the secrets, end user will create the secret
  destination:
    create: true
    name: db-secret

  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: postgres

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vault-auth
```

**Environment**
* Kubernetes version: 
  * EKS
* vault-secrets-operator version: 0.4.0
