### ISSUE TITLE
Labels not updating if was changed in VaultStaticSecret

### ISSUE THREAD

**Issue by timansky** [hashicorp/vault-secrets-operator#472]
**Describe the bug**
Changes to labels in CR VaultStaticSecret are not applying to destination secret.

**To Reproduce**
1. Create VaultStaticSecret with spec.destination.labels defined
```yaml
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: project-service-example
  namespace: example-namespace
  labels: &labels
    some: label
spec:
  vaultAuthRef: vault.cluster.local
  type: kv-v2
  mount: ${VAULT_SECRET_MOUNT}
  path: ${VAULT_SECRET_PATH}
  destination:
    create: true
    name: ${KUBE_SECRET_NAME}
    labels:
      *labels
```
 
3. Wait for operator to create secret
4. Modify spec.destination.labels in VaultStaticSecret and apply
5. Labels will not be applied to existing secret

**Expected behavior**
Any changes to VaultStaticSecret must be applied to destination secret

**Environment**
* Kubernetes version: vanila v1.26.4
* vault-secrets-operator version: 0.3.4
