### ISSUE TITLE
Rotate Credentials button in Static Role in VDS doesn't work for pods No rolling updates.

### ISSUE THREAD

**Issue by toasahi** [hashicorp/vault-secrets-operator#494]
![Group 1](https://github.com/hashicorp/vault-secrets-operator/assets/82006976/289f9653-de01-48d9-b11d-c7d3e20be53f)

**バグについて説明する**
The "Rotate credentials" button in the image changes the DataBase password, but not the pod environment variable (Secret). You will not be able to connect.
The reason is obvious: the values of "rotationPeriod" and "rotationSchedule" in the VaultStaticCredsMetaData are not changed from the values when VaultDynamicSecrets is applied.
Therefore, the pod does not perform a rolling update when the "Rotate credentials" button is pressed.
This will cause a big problem in the future.

**To Reproduce**
1. Enable database engine for postgres
2. Create static role
3. Apply the CRD of VSO.
4. Specify Deployment to be rotated for VDS
5. Press Rotate credential
6. Pods don't do rolling updates.

Application deployment:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-demo
  namespace: default
spec:
  allowStaticCreds: true
  # Mount path of the secrets backend
  mount: db/postgres

  # Path to the secret
  path: static-creds/postgres-role

  # Where to store the secrets, end user will create the secret
  destination:
    create: true
    name: db-secret

  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: postgres

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vault-auth
```

**期待される行動**
VDS(StaticRole) uses a single User, so when the RotateCredentials button is pressed, the Pod should do a rolling update and the Secret should be rewritten.

**Environment**
Kubernetes version:
EKS
vault: 1.15.1
vault-secrets-operator version: 0.4.0
postgres: 16.1.0
