### ISSUE TITLE
v0.4.1 very high cpu usage

### ISSUE THREAD

**Issue by rgarcia89** [hashicorp/vault-secrets-operator#495]
**Describe the bug**
After updating to v0.4.1 all nodes of the cluster have increased the cpu usage drastically.

**To Reproduce**
Update form v0.4.0 to v0.4.1

Application deployment:

```yaml
controller:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: vault-secrets-operator
        topologyKey: topology.kubernetes.io/zone
  replicas: 2
defaultAuthMethod:
  enabled: true
  kubernetes:
    role: vault-reader
  mount: k8s-cluster
defaultVaultConnection:
  address: https://vault.vault.svc.cluster.local:8200
  enabled: true
  skipTLSVerify: true
telemetry:
  serviceMonitor:
    enabled: true
```

**Environment**
* Kubernetes version: 1.26.6
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): AKS
  * Other configuration options or runtime services (istio, etc.):
* vault-secrets-operator version: v0.4.1

**Additional context**

According to the logs it looks like vso has triggered a sync of every secret constantly and restarted the related pod with that again and again.

![image](https://github.com/hashicorp/vault-secrets-operator/assets/4134730/7776e292-8c22-4aa7-bbbb-9f56c921fbf9)
