### ISSUE TITLE
Ability to add labels and annotations to secrets created by VSO

### ISSUE THREAD

**Issue by razahuss02** [hashicorp/vault-secrets-operator#518]
**Is your feature request related to a problem? Please describe.**
The ability to add labels and annotations to secrets created by VSO.

**Describe the solution you'd like**
```
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: example-vso-secret
spec:
  type: kv-v2
  mount: secret
  path: path
  destination:
    name: example-secret
    create: true
    labels:
      app.kubernetes.io/part-of: argocd
    annotations:
      reflector.v1.k8s.emberstack.com/auto-reflects: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth

```
