### ISSUE TITLE
Support syncing of configmaps?

### ISSUE THREAD

**Issue by nia-potato** [hashicorp/vault-secrets-operator#543]
**Is your feature request related to a problem? Please describe.**

Currently the vso crd is mainly used for syncing k8s secrets, but since this is a more k8s native flavored tool in hashicorp's tool box as compared to agent-inject and csi-mounts, would it be in scope to potentially to sync configmaps since configmaps  which are almost as sensitive when compared to secrets? 

**Describe the solution you'd like**

if we assume we already store configmaps in vault in a normal kv2 engine the vaultconfigmapspec could look like this: 
```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConfigmap
metadata:
  name: test-configmaps
  namespace: default
spec:
  destination:
    create: true
    name: test-configmaps
  mount: configmaps
  path: configmaps/test-configmaps
  refreshAfter: 60s
  type: kv-v2

```

**Comment by lukas-smiga** [comment]
Indeed this would be a nice feature (similar to advanced templating in External Secrets Operator), as many teams adopted a habit of using Vault for storing semi-sensitive information, i.e. configuration parameters, CA bundles, environments variables and such.

Also, maybe alternate approach might be to enrich existing VaultStaticSecret API with new a destination type of ConfigMap:

```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: test-configmaps
  namespace: default
spec:
  destination:
    create: true
    name: test-configmaps
    kind: ConfigMap
  mount: configmaps
  path: configmaps/test-configmaps
  refreshAfter: 60s
  type: kv-v2
```
