### ISSUE TITLE
permission denied for VaultStaticSecret for newer version

### ISSUE THREAD

**Issue by makas45** [hashicorp/vault-secrets-operator#577]
We have installed the vault-secrets-operator with version: 0.4.3 appVersion: "0.4.3" and used the below config to create staticsecret kind but we got the below error "2024-01-30T11:17:26Z	DEBUG	events	Failed to get Vault auth login: Error making API request.
URL: PUT https://vault-xxxxxx/v1/auth/vso/login
Code: 403. Errors:
permission denied	{"type": "Warning", "object": {"kind":"VaultStaticSecret","namespace":"xxxxx","name":"vault-static-secret","uid":"262896c9-6534-4a20-93b3-bca92237f17a","apiVersion":"secrets.hashicorp.com/v1beta1","resourceVersion":"513012396"}, "reason": "VaultClientConfigError"}
```
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: zz-workflows
  name: vault-connection
spec:
  address: https://vault-xxxxx
  skipTLSVerify: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: zz-workflows
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: vso
  kubernetes:
    role: vso-role
    serviceAccount: vault-auth
    audiences:
      - "https://container.googleapis.com/v1/projects/projectname/locations/europe-west4/clusters/clustername"
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
  namespace: zz-workflows
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path:  webapp
  refreshAfter: 10s
  destination:
    create: true
    name: vso-handled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: zz-workflows
```

```
The below config which we used for to create a auth for kubernetes and policy
➜  ~ vault secrets enable -path=secret kv-v2
Success! Enabled the kv-v2 secrets engine at: secret/
➜  ~
➜  ~ vault kv put kvv2/webapp username="web-user" password=":pa55word:"
== Secret Path ==
secret/data/webapp

======= Metadata =======
Key                Value
---                -----
created_time       2023-10-15T17:56:15.85914277Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1

Policy and role info:
➜  ~ vault policy write webapp-ro - <<EOF
path "kvv2/data/webapp" {
   capabilities = ["read"]
}
path "kvv2/metadata/webapp" {
   capabilities = ["read"]
}
EOF
Success! Uploaded policy: webapp-ro

➜  ~ vault auth enable -path=vso kubernetes
Success! Enabled kubernetes auth method at: vso/

➜  ~ vault write auth/vso/role/vso-role \
      bound_service_account_names=vault-auth \
      bound_service_account_namespaces=zz-workflows \
      policies=webapp-ro \
      ttl=24h
Success! Data written to: auth/vso/role/vso-role

➜  ~ vault write auth/vso/config \
      token_reviewer_jwt="$TOKEN_REVIEW_JWT" \
      kubernetes_host="$KUBE_HOST" \
      kubernetes_ca_cert="$KUBE_CA_CERT" \
      disable_issuer_verification=true
Success! Data written to: auth/vso/config
```

Application deployment:

Other useful info to include: `kubectl describe deployment <app>` and `kubectl describe <vso-custom-resource> <app>` output.
```
 k describe vaultstaticsecrets.secrets.hashicorp.com vault-static-secret 
Name:         vault-static-secret
Namespace:    zz-workflows
Labels:       <none>
Annotations:  <none>
API Version:  secrets.hashicorp.com/v1beta1
Kind:         VaultStaticSecret
Metadata:
  Creation Timestamp:  2024-01-29T12:12:10Z
  Generation:          1
  Resource Version:    513012396
  UID:                 262896c9-6534-4a20-93b3-bca92237f17a
Spec:
  Destination:
    Create:          true
    Name:            vso-handled
  Hmac Secret Data:  true
  Mount:             secret
  Path:              webapp
  Refresh After:     10s
  Type:              kv-v2
  Vault Auth Ref:    vault-auth
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Warning  VaultClientConfigError  15s (x176 over 43h)  VaultStaticSecret  Failed to get Vault auth login: Error making API request.

URL: PUT https://vault-xxx/v1/auth/vso/login
Code: 403. Errors:

* permission denied
```

**Expected behavior**
It should create a secret based on the staticsecret which we stored in vault 
**Environment**
* Kubernetes version: 
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): MGKE - kubernetes version - 1.27
  * Other configuration options or runtime services (istio, etc.):
* vault-secrets-operator version:  0.4.3  

**Additional context**
Add any other context about the problem here.****
