### ISSUE TITLE
Secrets (still) not being renewed occasionally

### ISSUE THREAD

**Issue by andrejvanderzee** [hashicorp/vault-secrets-operator#610]
Already reported here https://github.com/hashicorp/vault-secrets-operator/issues/364. Now on VSO version 0.4.3.

We keep having issues with secrets not being renewed by VSO. As a result, Vault revokes the secret and the consuming PODs  fail to authenticate. Note that it seems nondeterministic: In some edge-cases VSO just does not renew, although in many cases it works as expected.

For example this VDS:

```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: grafana-rds
  namespace: somenamespace
spec:
  destination:
    create: true
    name: grafana-vso-rds
  mount: shared/rds
  path: creds/eks-service-grafana-owner
  renewalPercent: 67
  revoke: true
  rolloutRestartTargets:
  - kind: Deployment
    name: grafana
  vaultAuthRef: grafana
```

Here the Vault role:

```
$ vault read shared/rds/roles/eks-service-grafana-owner
Key                      Value
---                      -----
creation_statements      [CREATE ROLE "{{name}}" WITH LOGIN INHERIT ENCRYPTED PASSWORD '{{password}}' ALTER ROLE "{{name}}" SET search_path = koperit, public GRANT grafana_owner TO "{{name}}"]
credential_type          password
db_name                  postgres
default_ttl              336h
max_ttl                  2191h30m
renew_statements         []
revocation_statements    [REVOKE grafana_owner FROM "{{name}}" DROP ROLE "{{name}}"]
rollback_statements      []
```

We already put the `max_ttl` very high to prevent this issue from occurring too often.

After we get failing authenticating PODs, we have to manually re-deploy the VDS and until eventually it breaks again.
