### ISSUE TITLE
VaultStaticSecret kind is not working on Argocd

### ISSUE THREAD

**Issue by makas45** [hashicorp/vault-secrets-operator#627]
We have created the vaultstaticsecret and created an argocd application for the same but we got the below error.

```
`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: managed-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: managed-operators/helmcharts/vault-secrets-operator
    repoURL: reponame
    targetRevision: {{ .Values.baseBranch }}
  syncPolicy:
    automated: {}
`
`apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    app.kubernetes.io/managed-by: imagepullsecret-patcher
  name: image-pull-secret
  namespace: zz-workflows
spec:
  destination:
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        ".dockerconfigjson":
          text: |
            {{`{{- $config := .Secrets | mustDeepCopy -}}`}}
            {{- $hostname := get $config "hostname" -}}
            {{- $_ := unset $config "hostname" -}}
            {{- $_ := set $config "auth" (list (get .Secrets "username") ":" (get .Secrets "password") | join "" | b64enc) -}}
            {{- dict "auths" (dict $hostname $config) | mustToJson -}}
    labels:
      vss: "true"
    create: true
    name: image-pull-secret
    overwrite: false
    type: kubernetes.io/dockerconfigjson
  hmacSecretData: true
  mount: secret
  path: image-pull-secret
  type: kv-v2
  namespace: openshift
  vaultAuthRef: vault-auth`
```
Error message
`
ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template vault-secrets-operator --namespace managed-operators --kube-version 1.28 <api versions removed> --include-crds` failed exit status 1: Error: parse error at (vault-secrets-operator/templates/vault-conn-auth.yaml:73): undefined variable "$config" Use --debug flag to render out invalid YAML Error: `
