### ISSUE TITLE
Breaking changes to v1beta1 VaultStaticSecret and VaultConnection CRDs cause failed upgrades after v0.5.0

### ISSUE THREAD

**Issue by kennedn** [hashicorp/vault-secrets-operator#631]
**Describe the bug**
Additional required fields have been added to the VaultConnection and VaultStaticSecret CRDS without bumping the api version:

https://github.com/hashicorp/vault-secrets-operator/blob/6de064379dc95617133056aca00213453a04f07b/chart/crds/secrets.hashicorp.com_vaultconnections.yaml#L59-L61

https://github.com/hashicorp/vault-secrets-operator/blob/6de064379dc95617133056aca00213453a04f07b/chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml#L178-L181

The new fields have default values but defaults are only applied when new instances of the CRDs are created. This means any in-flight CRD instances that exist in a given cluster will now break the operator and block the upgrade:

**To Reproduce**
1. Deploy a version of VSO older than v0.5.0
2. Deploy a VaultConnection or VaultStaticSecrets CRD
3. Upgrade the VSO operator past v0.5.0
6. Operator fails to upgrade:

![MicrosoftTeams-image](https://github.com/hashicorp/vault-secrets-operator/assets/8060657/d04dcb01-6843-4813-9bb5-a9a4a84c8f54)

Application deployment:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection-test
  namespace: default
spec:
  address: https://some-vault-url.com
  caCertSecretRef: some--ca-cert
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: default
  name: vault-static-secret-test
spec:
  vaultAuthRef: vault-auth-test
  mount: some-namespace/secret
  type: kv-v2
  path: sample
  refreshAfter: 60s
  destination:
    create: true
    name: vault-static-secret-test
```

**Expected behavior**
Operator upgrades successfully

**Environment**

* Kubernetes version: 
* OpenShift 4.14
* 
* vault-secrets-operator version:
* v0.5.1
