### ISSUE TITLE
strict decoding error: unknown field "spec.destination.transformation.templateSpecs"

### ISSUE THREAD

**Issue by MaximV93** [hashicorp/vault-secrets-operator#671]
**Describe the bug**

Yesterdag we removed VSO operator v4.0.0 from Openshift (4.13.34) and reinstalled VSO operator v5.0.2 using the operatorhub. Installation went fine. But when I try to apply a VaultStaticSecret with transformation I get the following error:

```
k apply -f testVaultStaticSecretTransformation.yml       
                                                                                                   
Error from server (BadRequest): error when creating "testVaultStaticSecretTransformation.yml ": VaultStaticSecret in version "v1beta1" cannot be handled as a VaultStaticSecret: strict decoding error: unknown field "spec.destination.transformation.templateSpecs
```

testVaultStaticSecretTransformation.yml

```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-test-b64secrets
spec:
  destination:
    create: true
    name: test-secret
    transformation:
      templateSpecs:
        test1:
          text: '{{- get .Secrets "keystore.jceks" | b64dec -}}'
  hmacSecretData: true
  mount: test-secrets/
  path: test/am-keystore
  refreshAfter: 30s
  type: kv-v2
  vaultAuthRef: vault-auth-test  
```

**Expected behavior**
I expect the VaultStaticSecret to be created.

**Environment**
* Kubernetes version: 
Openshift 4.13.34
* vault-secrets-operator version:
V0.5.2
**Additional context**

[(https://github.com/hashicorp/vault-secrets-operator/pull/437)] Someone else commented the same issue in this pull request. They had an issue with the CRD's but I expect those to be taken care of when installing the operator from the operatorhub?
