### ISSUE TITLE
Support for Kubernetes Secret stringData field

### ISSUE THREAD

**Issue by AlexanderK46** [hashicorp/vault-secrets-operator#690]
Kubernetes Secret [supports](https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret) 2 data fields - **data** (base64 encoded) and **stringData** (clear text content without base64 encoding). I use both data formats in my deployments and want to manage these Secrets using the Vault Secrets Operator.

Currently (v0.5.2) only the generation of secrets with the **data** field is supported. Generating secrets with the **stringData** field is not supported.

I would like to be able to specify in the **VaultStaticSecret** resource what data format should be used in the target Kubernetes Secret - data or stringData.

Example of the target Kubernetes Secret that I want to receive from the Operator
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth
```
