### ISSUE TITLE
Please Add UpdateStrategy

### ISSUE THREAD

**Issue by M-A-X-I-M** [hashicorp/vault-secrets-operator#692]
Please add to the values.yaml updateStrategy:
EXAMPLE:
```
  updateStrategy:
    type: RollingUpdate
    maxUnavailable: 1
    maxSurge: 1
```

and then in deployment.yaml
EXAMPLE:
```
spec:
  strategy:
    type: {{ .Values.updateStrategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.maxSurge }}
```
