### ISSUE TITLE
Support for Sprig htpasswd function

### ISSUE THREAD

**Issue by AlexanderK46** [hashicorp/vault-secrets-operator#693]
Sprig has an [htpasswd](http://masterminds.github.io/sprig/crypto.html#htpasswd) template function that would be really useful in secret transformation for configuring basic auth.

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: basic-auth
  namespace: test
spec:
  vaultAuthRef: test
  path: test
  type: kv-v2
  mount: test
  hmacSecretData: true
  refreshAfter: 1m
  destination:
    name: basic-auth
    create: true
    overwrite: true
    type: Opaque
    transformation:
      excludes:
        - .*
      templates:
        auth:
          text: '{{- htpasswd (get .Secrets "user") (get .Secrets "password") -}}'
```

Using VSO 0.5.2 there is an error: Failed to build K8s secret data: parse error: template: test/basic-auth/auth:1: function "htpasswd" not defined
