### ISSUE TITLE
DefaultVaultAuth is never generated for JWT-Auth

### ISSUE THREAD

**Issue by marc-aurel** [hashicorp/vault-secrets-operator#710]
**Describe the bug**
When enabled is set to "true" for "defaultAuthMethod" in the Helm values.yaml
and method and mount are set to '"jwt" I expect a VaultAuth-Object to be created.
But that never happens.

**To Reproduce**
1. Install Helm Chart application with the following values.yaml adaptations (these are the required values):
```
defaultAuthMethod:
  enabled: true
  method: jwt
  mount: jwt
  jwt:
    role: jwt-role
```
2. no VaultAuth-Object called "default" is created (like with VaultConnection)

**Expected behavior**
If "defaultAuthMethod" is enabled in values.yaml I expect
that a default VaultAuth is created.

**Environment**
* Kubernetes version: v1.26.14
* vault-secrets-operator version: 0.6.0
