### ISSUE TITLE
Vaultauth , service Account and Service Account token

### ISSUE THREAD

**Issue by raydenz** [hashicorp/vault-secrets-operator#745]
Hello 

I don't know if it is a bug or if i did not figure out how it exactly works.

I have installed vault secret (url : https://mysecret.local.com/)  and vault secret operator
I have configured a kubernetes authentification method

![image](https://github.com/hashicorp/vault-secrets-operator/assets/46000163/84b456c1-545e-4751-a140-83651da150d5)

I created a namespace called "myapp" (corresponding to "App Namespace" in the diagram)
and the 2 custom resources in "myapp" namespace :  VaultAuth and VaultStaticSecret 

Below the Vault Auth CR
```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: myapp
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: monapp
    serviceAccount: myapp-vault-sa 
    audiences:
      - https://mysecret.local.com/
```

**Everything works well!** 
My understanding is that vault operator will use the service account "myapp-vault-sa " to authenticate on Vault (via the Kubernetes authentification method), and Vault need the token corresponding to that service account to validate it on the API Server.

**My question :** 
I can't figure out how Vault can validate the token of my service account "myapp-vault-sa" whereas **i did not create a token/secret for the service account "myapp-vault-sa "**. 
It works but i don't know how is it possible without creating a token for the service account. (i already checked "kubectl get secret" etc.. )
How does it work exactly?

Please help

thank you ! :slight_smile:
