### ISSUE TITLE
Vault Operator resyncing secret when hmacSecretData has been set to false

### ISSUE THREAD

**Issue by bunniseng** [hashicorp/vault-secrets-operator#748]
**Describe the bug**

Vault operator is performing drift detection and resyncing the secret when setting hmacSecretData = false

**To Reproduce**
1. Create a VaultStaticSecret resource with hmacSecretData set to false
2. Once the secret is synced, update the hmacSecretData and reset back to false
3. Delete leading vault operator

Application deployment:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: test
  namespace: test
spec:
  destination:
    create: true
    name: test
    overwrite: false
  hmacSecretData: false
  mount: test
  path: test
  refreshAfter: 0s
  type: kv-v2
  vaultAuthRef: test
```

**Expected behavior**
When hmacSecretData is set to false, vault operator does not resync the secret in any event.

**Environment**
* Kubernetes version: 1.26
* vault-secrets-operator version: 0.6.0
