### ISSUE TITLE
when using defaultAuthMethod, the serviceaccount is looked up in the namespace where vaultstaticsecret is deployed

### ISSUE THREAD

**Issue by getkrabhijeet** [hashicorp/vault-secrets-operator#827]
**Describe the bug**
defaultAuthMethod is looking for the serviceaccount in the namespace where vaultstaticsecret is deployed. I guess since vaultAuth is reused for defaultAuthMethod, it ends up looking for serviceaccount in the namespace of vaultstaticsecret instead of operator namespace.

**To Reproduce**
1. Configure defaultAuthMethod while deploying VSO in a namespace "vso-namespace", this will result in VaultAuth named "default" to be created in vso-namespace.
2. We also create a serviceaccount named "vso-sa" in same namespace i.e. "vso-namespace"

```
  defaultAuthMethod:
    enabled: true
    namespace: ""
    allowedNamespaces: []
    method: jwt
    mount: jwt
    jwt:
      role: vso-role
      secretRef: ""
      serviceAccount: vso-sa
      tokenAudiences: ["vault"]
```
hashicorp vault configurations

vault secrets enable -path=kvv2 kv-v2
vault kv put kvv2/fed-grafana/admin-cred user="admin" password="admin123"

vault auth enable jwt

vault write auth/jwt/config \
   jwt_validation_pubkeys="-----BEGIN PUBLIC KEY-----
<Full Content of sa.pub key from k8s cluster>
-----END PUBLIC KEY-----"

Configure vault and create the needed policy and jwt role
vault policy write dev - <<EOF
path "kvv2/*" {
   capabilities = ["read"]
}
EOF

vault write auth/jwt/role/vso-role \
    role_type="jwt" \
    bound_audiences="vault" \
    user_claim="sub" \
    bound_subject="system:serviceaccount:vso-namespace:vso-sa" \
    policies="dev" \
    ttl="1h"

3. Create a VaultStaticSecret in a different namespace
```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-cred
  namespace: app-namespace
spec:
  destination:
    create: true
    name: admin-cred
    overwrite: false
  hmacSecretData: true
  mount: kvv2
  path: fed-grafana/admin-cred
  refreshAfter: 30s
  type: kv-v2
```

**Expected behavior**
The serviceaccount vso-sa created in vso-namespace should be used to fetch secrets from vault since that is the default auth method used. Secrets should be synced from vault to K8s cluster as kubernetes secret.

But here VSO complains that the serviceaccount is not found.

* vault-secrets-operator version: 0.7.1

**Additional context**
Error from VSO logs

{"level":"error","ts":"2024-06-20T13:23:19Z","msg":"Reconciler error","controller":"vaultstaticsecret","controllerGroup":"secrets.hashicorp.com","controllerKind":" │
│ VaultStaticSecret","VaultStaticSecret":{"name":"admin-cred","namespace":"app-namespace"},"namespace":"app-namespace","name":"admin-cred","reconcileID":"d83e480b-34e0-4ca1-9f84 │
│ -0507f5978807","error":"ServiceAccount \"vso-sa\" not found"}
