### ISSUE TITLE
VaultStaticSecret merge secrets from multiple path to one kubernetes secret

### ISSUE THREAD

**Issue by suxiaoxiaomm** [hashicorp/vault-secrets-operator#954]
**Is your feature request related to a problem? Please describe.**
We have one shared secret path for all services. And per service also has its specific secret path.

Could we use one VaultStaticSecret to merge multiple path into one Kubernetes secret?

```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: app
  name: app1-static-secret
spec:
  namespace: application
  mount: secret
  type: kv-v2
  path: 
    - app1/shared-secrets
    - app1/specific-secrets
  refreshAfter: 60s
  destination:
    create: true
    name: app-secret
```
