### ISSUE TITLE
Managing Vault resources other than secrets?

### ISSUE THREAD

**Issue by blakepettersson** [hashicorp/vault-secrets-operator#98]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to reconcile resources other than secrets, such as auth backends, mounts, policies etc etc...

**Describe the solution you'd like**
Custom CRDs for resources such as auth backends. It could look something like below

```yaml
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuthBackend
metadata:
  namespace: vso-example
  name: example
spec:
  vaultAuthRef: example
  type: "kubernetes"
  path: "kubernetes"
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultKubernetesAuthBackendConfig
metadata:
  namespace: vso-example
  name: example
spec:
  vaultAuthBackendRef: example
  issuer: some-issuer
  kubernetesHost: some-host
  kubernetesCaCert: some-cert
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultKubernetesAuthBackendRole
metadata:
  namespace: vso-example
  name: example
spec:
  vaultAuthBackendRef: example
  boundServiceAccountNames:
  - "*"
  boundServiceAccountNamespaces:
  - some-namespace
  tokenTtl: 3600
  tokenPolicies: 
 - some-policy
 audience: vault
```

**Describe alternatives you've considered**
There's always the possibility of using Crossplane and generating a Vault provider for it. There is also [vault-config-operator](https://github.com/redhat-cop/vault-config-operator). It would be great to have something which is fully supported by Hashicorp though.
