### ISSUE TITLE
[Helm] fullNameOverride and/or nameOverride have no effect

### ISSUE THREAD

**Issue by miguel-cardoso-mindera** [hashicorp/vault-secrets-operator#991]
**Describe the bug**
Installing this helm chart with a lengthily name causes the installation to fail because some resources have more than 63 characters.
Because I'm using ArgoCD, it uses the Application name as the release name, which causes it to be absurdly long. Trying to override this behaviour through  `fullNameOverride` or `nameOverride` have provided no effect

**To Reproduce**
1. Deploy helm with a long name, for example my own: `microservices-qa-new-vault-operator`
2. Try sync in Argocd
3. Sync fails:
`one or more objects failed to apply, reason: Service "microservices-qa-new-vault-operator-vault-secrets-operator-metrics-service" is invalid: metadata.name: Invalid value: "microservices-qa-new-vault-operator-vault-secrets-operator-metrics-service": must be no more than 63 characters`

Application deployment:

```yaml
fullNameOverride: vault-secrets-operator

controller:
  replicas: 1

  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scrape: "true"

  kubeRbacProxy:
    image:
      repository: quay.io/brancz/kube-rbac-proxy
      tag: v0.18.1
    
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi

  manager:
    image:
      repository: hashicorp/vault-secrets-operator
      tag: 0.9.1

    logging:
      level: info
      stacktraceLevel: panic

    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

  podSecurityContext:
    runAsNonRoot: true

hooks:
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

  upgradeCRDs:
    enabled: true
```

**Expected behavior**
I'd expect my kubernetes resources to be named `vault-secrets-operator-....`, instead it shows as `microservices-qa-new-vault-operator-vault-secrets-operator-...`

**Environment**
* Kubernetes version: not relevant
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): GKE
  * Other configuration options or runtime services (istio, etc.): not relevant
* vault-secrets-operator version: 0.9.1

**Additional context**
